### ISSUE TITLE
Add comment.char=""

### ISSUE THREAD

**Issue by brookstagg** [delabj/ACTmapR#1]
First let me say thanks for sharing this package. It has saved me a ton of time. Second, I would do a pull request to fix this, but I am new to collaborating on github, so trying to learn that. In your `ReadACT` function I have found it chokes on some of our ACT files. Adding `comment.char=""` to the `read.fwf` lines fixes the problem.

Thanks

```
ReadACT_new <- function (file = "fileName", year = "19-20", blanks = F, 
          scores_only = T) 
{
  df <- GetMapping(year)
  if (!is.data.frame(df)) {
    stop("Given Mapping isn't a dataframe. Have you entered the year correctly?")
  }
  temp <- read.fwf(file = file, widths = df$widthsACT, col.names = df$namesACT, comment.char="")
  if (blanks) {
    return(temp)
  }
  temp <- temp %>% select(-(starts_with("blank")))
  if (scores_only) {
    temp <- temp %>% select(lastName, firstName, dateOfBirth, 
                            stateID, testDate, composite = scaleComposite, english = scaleEnglish, 
                            mathmatics = scaleMath, reading = scaleReading, science = scaleScience, 
                            `writing subscore` = scoreWR)
  }
  return(temp)
}
```

**Comment by delabj** [comment]
I'll take a look at this, I'm actually rewriting the package at the moment as I was having some issues with using it on shinyapps. and I wanted to bring it more in line with the style guidlines from http://r-pkgs.had.co.nz/description.html


 I should be able to integrate that! If you have any  other suggestions, feel free to make a pull request or issue!

**Comment by delabj** [comment]
I've added this line to the code.

**Comment by brookstagg** [comment]
Awesome. Thanks!
